version: '3.8'

services:
  acme-dns-with-ui:
    image: ghcr.io/netzint/acme-dns:combined
    container_name: acme-dns-with-ui
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80"      # HTTP API + UI
      - "443:443"    # HTTPS API + UI (if TLS enabled)
    volumes:
      - ./config:/etc/acme-dns:ro
      - ./data:/var/lib/acme-dns
    environment:
      - TZ=Europe/Berlin
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"