version: '3.8'

services:
  acme-dns:
    image: ghcr.io/netzint/acme-dns:latest
    container_name: acme-dns
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80"
      - "443:443"
    volumes:
      - ./config:/etc/acme-dns:ro
      - ./data:/var/lib/acme-dns
    environment:
      - TZ=Europe/Berlin
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - acme-dns-net

networks:
  acme-dns-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24